name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  CI:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - uses: actions/checkout@v4
    - name: Setup do Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './src/package-lock.json'

    - name: Verifica a versão do Node.js
      run: node -v

    - name: Verifica a versão do npm
      run: npm -v
        
    - name: Instalação do Mocha e dos pacotes para teste
      run: |
        cd src
        npm install -g mocha
        npm install

    - name: Execução do teste
      run: mocha src/test/convert.js

    - name: Instalação de dependências
      run: cd src && npm ci

    - name: Build
      run: cd src && npm run build --if-present

    - name: Teste
      run: cd src && npm test
